# 0. 导入库

In [ ]:
import numpy as np

# 1. 数据生成

In [29]:
points_A = np.random.randint(0, 100, (5, 2))
points_B = np.random.randint(0, 100, (8, 2))
print("points_A:\n", points_A)
print("points_B: \n", points_B)

points_A:
 [[27 79]
 [66 84]
 [67  5]
 [46 38]
 [44 69]]
points_B: 
 [[95 51]
 [92 48]
 [57 70]
 [ 6 30]
 [70 25]
 [46 95]
 [33 65]
 [71 79]]


# 2. 距离矩阵计算

In [57]:
points_A = points_A.reshape(5, 1, 2)
points_B = points_B.reshape(1, 8, 2)
# 写法一：
# distance_matrix = np.sqrt((points_A[:,:,[0]] - points_B[:,:,[0]])**2 + (points_A[:,:,[1]] - points_B[:,:,[1]])**2).squeeze()
# 写法二：
diff = points_A - points_B
distance_matrix = np.sqrt(np.sum(diff**2, axis=-1))
# print("points_A:\n", points_A)
# print("points_B: \n", points_B)
print(distance_matrix)
print(distance_matrix.shape)

[[73.53910524 72.01388755 31.32091953 53.31041174 69.02897942 24.8394847
  15.23154621 44.        ]
 [43.93176527 44.40720662 16.64331698 80.72174428 59.13543777 22.82542442
  38.07886553  7.07106781]
 [53.85164807 49.73932046 65.76473219 65.9241989  20.22374842 92.4175308
  68.9637586  74.10802925]
 [50.69516742 47.07440918 33.83784863 40.79215611 27.29468813 57.
  29.96664813 48.02082881]
 [54.08326913 52.39274759 13.03840481 54.45181356 51.10772936 26.07680962
  11.70469991 28.7923601 ]]
(5, 8)


# 3. 轴向数据聚合

In [63]:
min_A_distance_matrix = np.min(distance_matrix, axis=1)
print(min_A_distance_matrix)

[15.23154621  7.07106781 20.22374842 27.29468813 11.70469991]


# 4. 复合条件查询

In [72]:
# 方法一：
min_B_distance_matrix = np.min(distance_matrix, axis=0)
print(min_B_distance_matrix)
mask = min_B_distance_matrix < 20
index = np.where(mask)
print(index)

[43.93176527 44.40720662 13.03840481 40.79215611 20.22374842 22.82542442
 11.70469991  7.07106781]
(array([2, 6, 7]),)


In [76]:
# 方法二：
mask = distance_matrix < 20
mask = np.any(mask, axis=0)
index = np.where(mask)
print(index)

(array([2, 6, 7]),)
